#!/bin/bash
mogrify -resize 1776x1276 /home/booth/photobooth_images/*.jpg
#mogrify -resize 1600x1200 /home/booth/photobooth_images/*.jpg
#montage /home/booth/photobooth_images/*.jpg /home/booth/temp_montage2.jpg
montage /home/booth/photobooth_images/*.jpg /home/booth/shuttermatic/photobooth_label.jpg -tile 2x1 -geometry +5+5 /home/booth/temp_montage3.jpg
value=$(<settings/printer.txt)
echo "$value"
if [ "$value" == "1" ]; then
echo "Sending to Printer"
lp -d MITSUBISHI_CK60D70D707D /home/booth/temp_montage3.jpg
else
echo "skipping printer"
fi
suffix=$(date +%H%M%S)
scp -v /home/booth/temp_montage3.jpg jimmy@192.168.10.10:/var/www/html/photos/Wedding_${suffix}.jpg
sudo cp /home/booth/temp_montage3.jpg /home/photobooth/booth_images/Archive_${suffix}.jpg
rm /home/booth/photobooth_images/*.jpg
rm /home/booth/temp*
