#!/bin/bash
mogrify -resize 1776x1276 /home/pi/photobooth_images/*.jpg
#montage /home/pi/photobooth_images/*.jpg /home/pi/temp_montage2.jpg
montage /home/pi/photobooth_images/*.jpg /home/pi/shuttermatic/photobooth_label.jpg -tile 2x1 -geometry +5+5 /home/pi/temp_montage3.jpg
value=$(<settings/printer.txt)
echo "$value"
if [ "$value" == "1" ]; then
echo "Sending to Printer"
lp -d Canon_1200 /home/pi/temp_montage3.jpg
else
echo "skipping printer"
fi
suffix=$(date +%H%M%S)
sudo cp /home/pi/temp_montage3.jpg /var/www/html/photobooth/PB_archive/PB_${suffix}.jpg
rm /home/pi/photobooth_images/*.jpg
rm /home/pi/temp*
